openapi: 3.1.0
paths:
  /api/v1/batch/arrivals:
    post:
      tags: [Batch]
      summary: Consultar estimaciones de múltiples paradas simultáneamente
      description: |
        Envía un array de `stopIds` y devuelve las estimaciones de llegada agrupadas para todas ellas.
        Reduce drásticamente la latencia de red si el cliente web necesita renderizar el estado de muchas paradas de una sola vez.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                stops:
                  type: array
                  items:
                    type: integer
            example:
              stops: [41, 42, 100]
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                success: true
                results:
                  "41":
                    - line: "LC"
                      estimate1: 5
                  "42":
                    - line: "1"
                      estimate1: 1
              schema:
                type: object
